apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisparr-pvc
  namespace: whisparr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisparr-download-pvc
  namespace: whisparr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
