apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-metallb
  namespace: argocd
spec:
  project: 2b99cceb
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.15.2
    helm:
      releaseName: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
