apiVersion: v1
kind: ConfigMap
metadata:
  name: tdarr-config
  namespace: tdarr
data:
  serverIP: "0.0.0.0"
  serverPort: "8266"
  webUIPort: "8265"
  internalNode: "true"
  inContainer: "true"
  ffmpegVersion: "7"
  nodeName: "MyInternalNode"
  auth: "false"
  openBrowser: "true"
  maxLogSizeMB: "10"
  cronPluginUpdate: ""
  TZ: "Europe/London"
  PUID: "1000"
  PGID: "1000"
  NVIDIA_DRIVER_CAPABILITIES: "all"
  NVIDIA_VISIBLE_DEVICES: "all"