apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tdarr-internal-certificate
  namespace: tdarr
spec:
  secretName: tdarr-internal-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  commonName: ltc.tsphotoclicks.net
  dnsNames:
    - "ltc.tsphotoclicks.net"
    - "*.ltc.tsphotoclicks.net"