apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-pvc
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server-pvc
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-logs-pvc
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-media-pvc
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: tdarr-media-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: ds.tsphotoclicks.net
    path: /volume1/video
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache-pvc
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: tdarr-cache-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: ds.tsphotoclicks.net
    path: /volume1/video/cache
  persistentVolumeReclaimPolicy: Retain