apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: prowlarr
        image: linuxserver/bazarr:1.5.2
        ports:
          - containerPort: 6767
        volumeMounts:
          - name: prowlarr-config
            mountPath: /config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi

      - name: gluetun
        image: qmcgaw/gluetun:v3.40.0
        env:
        - name: VPN_TYPE
          value: "openvpn"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_USER
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_PASSWORD
        - name: UPDATER_PERIOD
          value: "24h"
        - name: SERVER_COUNTRIES
          value: "United States"
        - name: VPN_SERVICE_PROVIDER
          value: "nordvpn"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 20
          failureThreshold: 5
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-pvc