apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: nzbget
  labels:
    app: nzbget
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nzbget
        image: nzbgetcom/nzbget:v25.2
        ports:
          - containerPort: 6789
        volumeMounts:
          - name: nzbget-config
            mountPath: /config
          - name: nzbget-downloads
            mountPath: /downloads
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 750m
            memory: 2Gi
      - name: gluetun
        image: qmcgaw/gluetun:v3.40.0
        env:
        - name: VPN_TYPE
          value: "openvpn"
        - name: VPN_SERVICE_PROVIDER
          value: "nordvpn"
        - name: SERVER_COUNTRIES
          value: "United States"
        - name: UPDATER_PERIOD
          value: "24h"
        - name: SHADOWSOCKS
          value: "on"
        - name: HTTPPROXY
          value: "on"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_USER
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_PASSWORD
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
        - name: nzbget-config
          persistentVolumeClaim:
            claimName: nzbget-pvc
        - name: nzbget-downloads
          persistentVolumeClaim:
            claimName: nzbget-download-pvc
