apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-internal-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-internal-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.tsphotoclicks.net