apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-longhorn
  namespace: argocd
spec:
  project: 2b99cceb

  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.9.1
    helm:
      releaseName: longhorn
      valuesObject:
        service:
          ui:
            type: ClusterIP
        persistence:
          reclaimPolicy: Retain

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
