ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.ltc.tsphotoclicks.net`)
    entryPoints:
      - websecure
    tls:
      secretName: traefik-internal-secret

providers:
  kubernetesGateway:
    enabled: true
  kubernetesCRD:
    allowCrossNamespace: true

gateway:
  namespacePolicy: All

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
