ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.tsphotoclicks.net`)
    entryPoints:
      - websecure

providers:
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
