ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.tsphotoclicks.net`)
    entryPoints:
      - websecure

providers:
  kubernetesGateway:
    enabled: true
gateway:
  namespacePolicy: All

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
