apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-certmanager
  namespace: argocd
spec:
  project: 2b99cceb

  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.18.2
    helm:
      releaseName: cert-manager
      valuesObject:
        namespace: cert-manager
        crds:
          enabled: true
        extraArgs:
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
