apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-authentik
  namespace: argocd
spec:
  project: 2b99cceb

  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.8.4
    helm:
      releaseName: authentik
      valuesObject:
        authentik:
          secret_key: ""
          postgresql:
            password: ""

        server:
          ingress:
            # Specify kubernetes ingress controller class name
            ingressClassName: traefik
            enabled: true
            hosts:
              - authentik.ltc.tsphotoclicks.net
            tls:
              - secretName: authentik-internal-secret
                hosts:
                  - "ltc.tsphotoclicks.net"
                  - "*.ltc.tsphotoclicks.net"

        postgresql:
          enabled: true
          auth:
            password: ""
        redis:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
