apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-authentik
  namespace: argocd
spec:
  project: 2b99cceb

  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.6
    helm:
      releaseName: authentik
      valuesFrom:
        - secretRef:
            name: authentik-secret
          valuesKey: AUTHENTIK_SECRET_KEY
          targetPath: authentik.secret_key
        - secretRef:
            name: authentik-secret
          valuesKey: AUTHENTIK_POSTGRES_PASSWORD
          targetPath: authentik.postgresql.password
        - secretRef:
            name: authentik-secret
          valuesKey: AUTHENTIK_POSTGRES_PASSWORD
          targetPath: postgresql.auth.password
      values: |
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - authentik.ltc.tsphotoclicks.net
            tls:    
              - secretName: authentik-internal-secret
                hosts:
                  - "ltc.tsphotoclicks.net"
                  - "*.ltc.tsphotoclicks.net"

        postgresql:
          enabled: true
        redis:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
