apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-media
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: k3s-media-bazarr
        path: media/bazarr
        namespace: bazarr
      - name: k3s-media-emby
        path: media/emby
        namespace: emby
      - name: k3s-media-gluetun
        path: media/gluetun
        namespace: gluetun
      - name: k3s-media-jellyfin
        path: media/jellyfin
        namespace: jellyfin
      - name: k3s-media-qbittorrent
        path: media/qbittorrent
        namespace: qbittorrent
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: 2b99cceb
      source:
        repoURL: https://github.com/torchilidae/k3s-harness.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

