apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-media
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: k3s-media-bazarr
        path: media/bazarr
        namespace: bazarr
      - name: k3s-media-emby
        path: media/emby
        namespace: emby
      - name: k3s-media-flaresolverr
        path: media/flaresolverr
        namespace: flaresolverr
      - name: k3s-media-gluetun
        path: media/gluetun
        namespace: gluetun
      - name: k3s-media-jellyfin
        path: media/jellyfin
        namespace: jellyfin
      - name: k3s-media-jellyseerr
        path: media/jellyseerr
        namespace: jellyseerr
      - name: k3s-media-prowlarr
        path: media/prowlarr
        namespace: prowlarr
      - name: k3s-media-qbittorrent
        path: media/qbittorrent
        namespace: qbittorrent
      - name: k3s-media-radarr
        path: media/radarr
        namespace: radarr
      - name: k3s-media-sabnzbd
        path: media/sabnzbd
        namespace: sabnzbd
      - name: k3s-media-sonarr
        path: media/sonarr
        namespace: sonarr
      - name: k3s-media-tdarr
        path: media/tdarr
        namespace: tdarr
      - name: k3s-media-whisparr
        path: media/whisparr
        namespace: whisparr
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: 2b99cceb
      source:
        repoURL: https://github.com/torchilidae/k3s-harness.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

