apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-internal-certificate
  namespace: sabnzbd
spec:
  secretName: sabnzbd-internal-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  commonName: ltc.tsphotoclicks.net
  dnsNames:
    - "ltc.tsphotoclicks.net"
    - "*.ltc.tsphotoclicks.net"