apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: flaresolverr
  labels:
    app: flaresolverr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
        media-app: authorized
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: flaresolverr
        image: flaresolverr/flaresolverr:v3.3.25
        ports:
        - containerPort: 8191
        env:
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
