apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-pvc
  namespace: uptimekuma
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
