apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptimekuma
  namespace: uptimekuma
  labels:
    app: uptimekuma
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: uptimekuma
  template:
    metadata:
      labels:
        app: uptimekuma
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: uptimekuma
          image: louislam/uptime-kuma:1.23.16
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: uptimekuma-data
              mountPath: /app/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 768Mi
      volumes:
        - name: uptimekuma-data
          persistentVolumeClaim:
            claimName: uptimekuma-pvc