apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyseerr.yaml
  - jellyseerr-certificate.yaml
  - jellyseerr-ingressroute.yaml
  - jellyseerr-namespace.yaml
  - jellyseerr-storage.yaml