apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-traefik
  namespace: argocd
spec:
  project: 2b99cceb

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      valuesObject:
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.ltc.tsphotoclicks.net`)
            entryPoints:
              - websecure
            middlewares:
              - name: authentik-middleware
                namespace: authentik
            tls:
              secretName: traefik-internal-secret

        providers:
          kubernetesGateway:
            enabled: true
          kubernetesCRD:
            allowCrossNamespace: true

        gateway:
          namespacePolicy: All

        ports:
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
        deployment:
          podLabels:
            media-app: authorized

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
