apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyfin.yaml
  - jellyfin-certificate.yaml
  - jellyfin-ingressroute.yaml
  - jellyfin-namespace.yaml
  - jellyfin-storage.yaml