apiVersion: v1
kind: Service
metadata:
  name: rancher-lb
  namespace: cattle-system
spec:
  type: LoadBalancer
  selector:
    app: rancher
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
