apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-storage
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: k3s-storage-longhorn
        path: longhorn
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: 2b99cceb
      source:
        repoURL: https://github.com/torchilidae/k3s-harness.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

