apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-main
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: k3s-main-media
        path: media
      - name: k3s-main-monitor
        path: monitor
      - name: k3s-main-network
        path: network
      # - name: k3s-main-security
      #   path: security
      - name: k3s-main-storage
        path: storage
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: 2b99cceb
      source:
        repoURL: https://github.com/torchilidae/k3s-harness.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

