apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-tvshows-pvc
  namespace: emby
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: emby-tvshows-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-tvshows-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: ds.tsphotoclicks.net
    path: /volume1/video/TVShow
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-movies-pvc
  namespace: emby
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: emby-movies-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-movies-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: ds.tsphotoclicks.net
    path: /volume1/video/Movie
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-pvc
  namespace: emby
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: emby-pv
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emby-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: emby
---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: emby
  namespace: longhorn-system
spec:
  size: "2147483648"
  numberOfReplicas: 3
  staleReplicaTimeout: 30
  frontend: blockdev
  accessMode: rwx