apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: gluetun
spec:
  selector:
    app: gluetun
  ports:
    - name: socks5
      port: 8388
      targetPort: 8388
    - name: http
      port: 8888
      targetPort: 8888
