apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: gluetun
  labels:
    app: gluetun
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gluetun
        image: qmcgaw/gluetun
        ports:
        - containerPort: 1080
        - containerPort: 8000
        env:
        - name: VPN_TYPE
          value: "openvpn"
        - name: VPN_SERVICE_PROVIDER
          value: "nordvpn"
        - name: SERVER_COUNTRIES
          value: "United States"
        - name: UPDATER_PERIOD
          value: "24h"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_USER
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_PASSWORD
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
