apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: gluetun
  labels:
    app: gluetun
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:v3.40.0
        ports:
        - name: http
          containerPort: 8388
        - name: shadowsocks
          containerPort: 8888
        - name: healthcheck
          containerPort: 8000
        volumeMounts:
        - name: gluetun-config
          mountPath: /gluetun/auth/config.toml
          subPath: config.toml
        env:
        - name: VPN_TYPE
          value: "openvpn"
        - name: VPN_SERVICE_PROVIDER
          value: "nordvpn"
        - name: SERVER_COUNTRIES
          value: "United States"
        - name: UPDATER_PERIOD
          value: "24h"
        - name: SHADOWSOCKS
          value: "on"
        - name: HTTPPROXY
          value: "on"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_USER
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_PASSWORD
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 768Mi
      volumes:
        - name: gluetun-config
          configMap:
            name: gluetun-config
