apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: bazarr
  labels:
    app: bazarr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bazarr
        image: linuxserver/bazarr:1.5.2
        ports:
          - containerPort: 6767
        volumeMounts:
          - name: bazarr-config
            mountPath: /config
          - name: bazarr-tvshows
            mountPath: /tv
          - name: bazarr-movies
            mountPath: /movies
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

      - name: gluetun
        image: qmcgaw/gluetun:v3.40.0
        env:
        - name: VPN_TYPE
          value: "openvpn"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_USER
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openvpn-secrets
              key: OPENVPN_PASSWORD
        - name: UPDATER_PERIOD
          value: "24h"
        - name: SERVER_COUNTRIES
          value: "United States"
        - name: VPN_SERVICE_PROVIDER
          value: "nordvpn"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 20
          failureThreshold: 5

      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-pvc
        - name: bazarr-tvshows
          persistentVolumeClaim:
            claimName: bazarr-tvshows-pvc
        - name: bazarr-movies
          persistentVolumeClaim:
            claimName: bazarr-movies-pvc