name: Sync Cert Manager Manifest

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  cert-manager-sync:
    name: Cert Manager sync check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest Cert Manager manifest
        run: |
          mkdir -p network/cert-manager
          version=$(curl -s https://api.github.com/repos/cert-manager/cert-manager/releases/latest | jq -r .tag_name)
          echo "Latest version: $version"
          curl -sSL https://github.com/cert-manager/cert-manager/releases/download/$version/cert-manager.yaml \
            -o network/cert-manager/cert-manager.yaml

      - name: Check if file changed
        id: diffcheck
        run: |
          if git diff --quiet network/cert-manager/cert-manager.yaml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if file changed
        if: steps.diffcheck.outputs.changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add network/cert-manager/cert-manager.yaml
          git commit -m "Auto-sync: Update Cert Manager manifest"
          git push
